<?php
/**
 * CLI installer for modernized vichan (PHP 8.1+ / PostgreSQL only).
 *
 * Usage (from repo root):
 *   php tools/install_cli.php
 *   php tools/install_cli.php --force
 *
 * Environment overrides:
 *   VICHAN_DB_HOST, VICHAN_DB_PORT, VICHAN_DB_NAME,
 *   VICHAN_DB_USER, VICHAN_DB_PASSWORD
 */

if (PHP_SAPI !== 'cli') {
	fwrite(STDERR, "This installer must be run from the command line.\n");
	exit(1);
}

chdir(dirname(__DIR__));

$force = in_array('--force', $argv, true);
$rewrite_secrets = in_array('--rewrite-secrets', $argv, true);

echo "vichan CLI installer\n";
echo "PHP " . PHP_VERSION . "\n";

// Composer/vendor not required

// Polyfill gettext for early config load if extension missing
if (!function_exists('_')) {
	function _(string $s): string { return $s; }
}

// Ensure cache dirs
foreach (['templates/cache', 'templates/cache_php', 'tmp/cache', 'tmp/locks'] as $dir) {
	if (!is_dir($dir) && !mkdir($dir, 0775, true) && !is_dir($dir)) {
		fwrite(STDERR, "Could not create $dir\n");
		exit(1);
	}
}

// Generate secrets if missing
$secrets_path = 'inc/secrets.php';
if (!is_readable($secrets_path) || filesize($secrets_path) < 50 || $rewrite_secrets) {
	// Use --rewrite-secrets to regenerate salts/credentials (logs everyone out).
	$db_type = 'pgsql';
	$db_host = getenv('VICHAN_DB_HOST') ?: '127.0.0.1';
	$db_port = getenv('VICHAN_DB_PORT') ?: '5432';
	$db_name = getenv('VICHAN_DB_NAME') ?: 'vichan';
	$db_user = getenv('VICHAN_DB_USER') ?: 'postgres';
	$db_pass = getenv('VICHAN_DB_PASSWORD') ?: 'adelia';

	$cookie_salt = 'OSSL.' . base64_encode(random_bytes(64));
	$trip_salt = 'OSSL.' . base64_encode(random_bytes(64));

	// Escape for single-quoted PHP strings
	$esc = static function (string $s): string {
		return str_replace(['\\', "'"], ['\\\\', "\\'"], $s);
	};

	$secrets = "<?php\n"
		. "/**\n * Local secrets — do not commit. Generated by tools/install_cli.php\n */\n\n"
		. "defined('TINYBOARD') or exit;\n\n"
		. "\$config['db']['type']     = '" . $esc($db_type) . "';\n"
		. "\$config['db']['server']   = '" . $esc($db_host) . "';\n"
		. "\$config['db']['port']     = '" . $esc($db_port) . "';\n"
		. "\$config['db']['database'] = '" . $esc($db_name) . "';\n"
		. "\$config['db']['user']     = '" . $esc($db_user) . "';\n"
		. "\$config['db']['password'] = '" . $esc($db_pass) . "';\n\n"
		. "\$config['cookies']['secure_login_only'] = 0;\n"
		. "\$config['cookies']['salt'] = '" . $esc($cookie_salt) . "';\n"
		. "\$config['secure_trip_salt'] = '" . $esc($trip_salt) . "';\n\n"
		. "\$config['debug'] = false;\n"
		. "\$config['verbose_errors'] = false;\n";

	if (file_put_contents($secrets_path, $secrets) === false) {
		fwrite(STDERR, "Could not write $secrets_path\n");
		exit(1);
	}
	echo "Wrote $secrets_path\n";
} else {
	echo "Using existing $secrets_path\n";
}

// Create PostgreSQL database before app connects to it
$db_type = 'pgsql';
$db_host = getenv('VICHAN_DB_HOST') ?: '127.0.0.1';
$db_port = getenv('VICHAN_DB_PORT') ?: '5432';
$db_name = getenv('VICHAN_DB_NAME') ?: 'vichan';
$db_user = getenv('VICHAN_DB_USER') ?: 'postgres';
$db_pass = getenv('VICHAN_DB_PASSWORD') ?: 'adelia';

// Prefer values from secrets.php if present
$secrets_src = file_get_contents($secrets_path);
if (preg_match("/\\\$config\\['db'\\]\\['server'\\]\\s*=\\s*'([^']+)'/", $secrets_src, $m)) {
	$db_host = $m[1];
}
if (preg_match("/\\\$config\\['db'\\]\\['port'\\]\\s*=\\s*'([^']+)'/", $secrets_src, $m)) {
	$db_port = $m[1];
}
if (preg_match("/\\\$config\\['db'\\]\\['database'\\]\\s*=\\s*'([^']+)'/", $secrets_src, $m)) {
	$db_name = $m[1];
}
if (preg_match("/\\\$config\\['db'\\]\\['user'\\]\\s*=\\s*'([^']+)'/", $secrets_src, $m)) {
	$db_user = $m[1];
}
if (preg_match("/\\\$config\\['db'\\]\\['password'\\]\\s*=\\s*'([^']+)'/", $secrets_src, $m)) {
	$db_pass = $m[1];
}

echo "DB: PostgreSQL  host=$db_host:$db_port  database=$db_name  user=$db_user\n";

try {
	$admin = new PDO(
		"pgsql:host={$db_host};port={$db_port};dbname=postgres",
		$db_user,
		$db_pass,
		[PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
	);
	$exists = $admin->query('SELECT 1 FROM pg_database WHERE datname = ' . $admin->quote($db_name))->fetchColumn();
	if (!$exists) {
		$name = preg_replace('/[^a-zA-Z0-9_]/', '', $db_name);
		if ($name === '') {
			throw new RuntimeException('Invalid database name');
		}
		$admin->exec('CREATE DATABASE ' . $name . " ENCODING 'UTF8'");
		echo "Created database {$name}\n";
	} else {
		echo "Database {$db_name} already exists\n";
	}
} catch (Throwable $e) {
	fwrite(STDERR, "PostgreSQL connection failed: " . $e->getMessage() . "\n");
	exit(1);
}

// Fake web environment for code that expects it
if (!isset($_SERVER['SERVER_NAME'])) {
	$_SERVER['SERVER_NAME'] = 'localhost';
}
if (!isset($_SERVER['REQUEST_METHOD'])) {
	$_SERVER['REQUEST_METHOD'] = 'GET';
}

// Full bootstrap (defines TINYBOARD, loadConfig, etc.)
require 'inc/bootstrap.php';

global $config, $pdo;

echo "App bootstrap OK\n";
sql_open();
echo "Connected OK\n";

if (file_exists($config['has_installed']) && !$force) {
	echo "Already installed (" . trim((string)file_get_contents($config['has_installed'])) . "). Use --force to re-run schema.\n";
	exit(0);
}

$sql_path = db_install_sql_path();
$sql = file_get_contents($sql_path);
if ($sql === false) {
	fwrite(STDERR, "Could not read $sql_path\n");
	exit(1);
}

echo "Applying schema from $sql_path ...\n";
$errors = 0;
foreach (db_split_sql_statements($sql) as $stmt) {
	try {
		$pdo->exec($stmt);
	} catch (Throwable $e) {
		$msg = $e->getMessage();
		if (stripos($msg, 'already exists') !== false) {
			continue;
		}
		echo "  WARN: " . $msg . "\n";
		echo "    near: " . substr(preg_replace('/\s+/', ' ', $stmt), 0, 120) . "\n";
		$errors++;
	}
}

echo "Creating posts_b ...\n";
$posts_sql = Element(db_schema_template('posts'), ['board' => 'b']);
foreach (db_split_sql_statements($posts_sql) as $stmt) {
	try {
		$pdo->exec($stmt);
	} catch (Throwable $e) {
		if (stripos($e->getMessage(), 'already exists') === false) {
			echo "  WARN: " . $e->getMessage() . "\n";
			$errors++;
		}
	}
}

try {
	if (function_exists('buildJavascript')) {
		buildJavascript();
		echo "Built main.js\n";
	}
	$boards = listBoards();
	foreach ($boards as $_board) {
		setupBoard($_board);
		if (function_exists('buildIndex')) {
			buildIndex();
		}
		echo "Board /{$_board['uri']}/ ready\n";
	}
	if (function_exists('rebuild_boards_list')) {
		rebuild_boards_list();
		echo "Wrote boards.html\n";
	}
	if (function_exists('ensure_landing_page')) {
		ensure_landing_page();
		echo "Landing page ready (index.html — edit freely)\n";
	}
	if (function_exists('rebuild_catalog')) {
		rebuild_catalog(false);
		echo "Catalogs built\n";
	}
} catch (Throwable $e) {
	echo "Post-schema setup warning: " . $e->getMessage() . "\n";
	echo $e->getTraceAsString() . "\n";
}

$version = '5.2.2-php85-pgsql';
file_put_contents($config['has_installed'], $version);
echo "Wrote {$config['has_installed']} ($version)\n";
echo "Done" . ($errors ? " with $errors warning(s)" : '') . ".\n";
echo "Log in at mod.php — default admin / password (change immediately).\n";
echo "Landing: edit index.html (example: examples/landing.html). Catalog: /b/catalog.html\n";
