

/* gettext-compatible _ function, example of usage:
 *
 * > // Loading pl_PL.json here (containing polish translation strings generated by tools/i18n_compile.php)
 * > alert(_("Hello!"));
 * Witaj!
 */
function _(s) {
	return (typeof l10n != 'undefined' && typeof l10n[s] != 'undefined') ? l10n[s] : s;
}

/* printf-like formatting function, example of usage:
 *
 * > alert(fmt("There are {0} birds on {1} trees", [3,4]));
 * There are 3 birds on 4 trees
 * > // Loading pl_PL.json here (containing polish translation strings generated by tools/locale_compile.php)
 * > alert(fmt(_("{0} users"), [3]));
 * 3 uzytkownikow
 */
function fmt(s, a) {
	return s.replace(/\{([0-9]+)\}/g, function(x) { return a[x[1]]; });
}

function until(timestamp) {
	let difference = timestamp - Date.now() / 1000 | 0;
	switch (true) {
	case (difference < 60):
		return "" + difference + ' ' + _('second(s)');
	case (difference < 3600): // 60 * 60 = 3600
		return "" + Math.round(difference / 60) + ' ' + _('minute(s)');
	case (difference < 86400): // 60 * 60 * 24 = 86400
		return "" + Math.round(difference / 3600) + ' ' + _('hour(s)');
	case (difference < 604800): // 60 * 60 * 24 * 7 = 604800
		return "" + Math.round(difference / 86400) + ' ' + _('day(s)');
	case (difference < 31536000): // 60 * 60 * 24 * 365 = 31536000
		return "" + Math.round(difference / 604800) + ' ' + _('week(s)');
	default:
		return "" + Math.round(difference / 31536000) + ' ' + _('year(s)');
	}
}

function ago(timestamp) {
	let difference = (Date.now() / 1000 | 0) - timestamp;
	switch (true) {
	case (difference < 60):
		return "" + difference + ' ' + _('second(s)');
	case (difference < 3600): /// 60 * 60 = 3600
		return "" + Math.round(difference/(60)) + ' ' + _('minute(s)');
	case (difference < 86400): // 60 * 60 * 24 = 86400
		return "" + Math.round(difference/(3600)) + ' ' + _('hour(s)');
	case (difference < 604800): // 60 * 60 * 24 * 7 = 604800
		return "" + Math.round(difference/(86400)) + ' ' + _('day(s)');
	case (difference < 31536000): // 60 * 60 * 24 * 365 = 31536000
		return "" + Math.round(difference/(604800)) + ' ' + _('week(s)');
	default:
		return "" + Math.round(difference/(31536000)) + ' ' + _('year(s)');
	}
}

var datelocale =
	{ days: [_('Sunday'), _('Monday'), _('Tuesday'), _('Wednesday'), _('Thursday'), _('Friday'), _('Saturday')]
	, shortDays: [_("Sun"), _("Mon"), _("Tue"), _("Wed"), _("Thu"), _("Fri"), _("Sat")]
	, months: [_('January'), _('February'), _('March'), _('April'), _('May'), _('June'), _('July'), _('August'), _('September'), _('October'), _('November'), _('December')]
	, shortMonths: [_('Jan'), _('Feb'), _('Mar'), _('Apr'), _('May'), _('Jun'), _('Jul'), _('Aug'), _('Sep'), _('Oct'), _('Nov'), _('Dec')]
	, AM: _('AM')
	, PM: _('PM')
	, am: _('am')
	, pm: _('pm')
	};


function alert(a, do_confirm, confirm_ok_action, confirm_cancel_action) {
	let handler = document.createElement('div');
	handler.id = 'alert_handler';
	handler.style.display = 'none';
	handler.style.opacity = '0';
	handler.style.transition = 'opacity 0.25s ease';

	let close = function() {
		handler.style.opacity = '0';
		setTimeout(function() {
			if (handler.parentNode) {
				handler.parentNode.removeChild(handler);
			}
		}, 250);
		return false;
	};

	let bg = document.createElement('div');
	bg.id = 'alert_background';
	handler.appendChild(bg);

	let div = document.createElement('div');
	div.id = 'alert_div';
	handler.appendChild(div);

	let closebtn = document.createElement('a');
	closebtn.id = 'alert_close';
	closebtn.href = '#';
	closebtn.innerHTML = '<i class="fa fa-times"></i>';
	closebtn.addEventListener('click', function(e) { e.preventDefault(); close(); });
	div.appendChild(closebtn);

	let msg = document.createElement('div');
	msg.id = 'alert_message';
	// Trusted app strings only — do not pass unescaped user HTML here.
	if (typeof a === 'string') {
		msg.textContent = a;
	} else if (a && a.nodeType) {
		msg.appendChild(a);
	} else {
		msg.textContent = String(a);
	}
	div.appendChild(msg);

	let okbtn = document.createElement('button');
	okbtn.className = 'button alert_button';
	okbtn.textContent = _('OK');
	div.appendChild(okbtn);

	if (do_confirm) {
		confirm_ok_action = (typeof confirm_ok_action !== 'function') ? function(){} : confirm_ok_action;
		confirm_cancel_action = (typeof confirm_cancel_action !== 'function') ? function(){} : confirm_cancel_action;
		okbtn.addEventListener('click', confirm_ok_action);
		let cancelbtn = document.createElement('button');
		cancelbtn.className = 'button alert_button';
		cancelbtn.textContent = _('Cancel');
		cancelbtn.addEventListener('click', function() { confirm_cancel_action(); close(); });
		div.appendChild(cancelbtn);
		bg.addEventListener('click', function() { confirm_cancel_action(); close(); });
		closebtn.addEventListener('click', function() { confirm_cancel_action(); });
	}

	bg.addEventListener('click', close);
	okbtn.addEventListener('click', close);

	document.body.appendChild(handler);
	// force reflow then show
	void handler.offsetWidth;
	handler.style.display = 'block';
	handler.style.opacity = '1';
}

var saved = {};


var selectedstyle = 'Yotsuba B';
var styles = {
	
	'Yotsuba B' : '',
	'Yotsuba C' : '/stylesheets/yotsuba_b.css',
	'Yotsuba' : '/stylesheets/yotsuba.css',
	'Futaba' : '/stylesheets/futaba.css',
	'Futaba Light' : '/stylesheets/futaba-light.css',
	'Burichan' : '/stylesheets/burichan.css',
	'Dark' : '/stylesheets/dark.css',
	'Tomorrow' : '/stylesheets/tomorrow.css',
	'Terminal' : '/stylesheets/terminal2.css',
	'Green Dark' : '/stylesheets/greendark.css',
	'Miku' : '/stylesheets/miku.css',
	'Pink' : '/stylesheets/pink.css',
	'Photon' : '/stylesheets/photon.css',
	'Notsuba' : '/stylesheets/notsuba.css',
	
};

if (typeof board_name === 'undefined') {
	var board_name = false;
}

function changeStyle(styleName, link) {
	
	
		localStorage.stylesheet = styleName;
	
	

	// Theme overlay (id=stylesheet); base style.css stays loaded separately.
	let mainStylesheetElement = document.getElementById('stylesheet');
	if (!mainStylesheetElement) {
		mainStylesheetElement = document.createElement('link');
		mainStylesheetElement.rel = 'stylesheet';
		mainStylesheetElement.type = 'text/css';
		mainStylesheetElement.id = 'stylesheet';
		document.getElementsByTagName('head')[0].appendChild(mainStylesheetElement);
	}

	let style = styles[styleName];
	if (typeof style === 'undefined') {
		return;
	}

	if (style === '' || style === null) {
		// Base theme only — disable overlay
		mainStylesheetElement.href = '';
		mainStylesheetElement.media = 'none';
		mainStylesheetElement.disabled = true;
	} else {
		mainStylesheetElement.disabled = false;
		mainStylesheetElement.media = 'all';
		mainStylesheetElement.href = style + `?v=${resourceVersion}`;
	}

	selectedstyle = styleName;

	// Keep top-left <select> in sync
	let sel = document.getElementById('style-select-dropdown');
	if (sel && sel.value !== styleName) {
		sel.value = styleName;
	}

	try {
		window.dispatchEvent(new CustomEvent('stylesheet', { detail: styleName }));
	} catch (e) { /* older browsers */ }
}



var resourceVersion = document.currentScript.getAttribute('data-resource-version');

	
	if (localStorage.stylesheet) {
		for (let styleName in styles) {
			if (styleName == localStorage.stylesheet) {
				changeStyle(styleName);
				break;
			}
		}
	}
	



function initStyleChooser() {
	// Theme dropdown at top of page (scrolls with content; not sticky)
	if (document.getElementById('style-select-wrap')) {
		return;
	}

	let wrap = document.createElement('div');
	wrap.id = 'style-select-wrap';
	wrap.setAttribute('role', 'navigation');

	let select = document.createElement('select');
	select.id = 'style-select-dropdown';
	select.title = _('Stylesheet');
	select.setAttribute('aria-label', _('Stylesheet'));

	for (let styleName in styles) {
		if (!Object.prototype.hasOwnProperty.call(styles, styleName)) {
			continue;
		}
		let opt = document.createElement('option');
		opt.value = styleName;
		opt.textContent = styleName;
		if (styleName === selectedstyle) {
			opt.selected = true;
		}
		select.appendChild(opt);
	}

	select.addEventListener('change', function () {
		changeStyle(this.value);
	});

	wrap.appendChild(select);

	let body = document.getElementsByTagName('body')[0];
	if (body.firstChild) {
		body.insertBefore(wrap, body.firstChild);
	} else {
		body.appendChild(wrap);
	}
}

function getCookie(cookie_name) {
	let results = document.cookie.match('(^|;) ?' + cookie_name + '=([^;]*)(;|$)');
	if (results) {
		return decodeURIComponent(results[2]);
	} else {
		return null;
	}
}
// Legacy alias used by older scripts / captcha helpers
function get_cookie(cookie_name) {
	return getCookie(cookie_name);
}





function highlightReply(id) {
	if (typeof window.event != "undefined" && event.which == 2) {
		// don't highlight on middle click
		return true;
	}

	let divs = document.getElementsByTagName('div');
	for (let i = 0; i < divs.length; i++) {
		if (divs[i].className.indexOf('post') != -1) {
			divs[i].className = divs[i].className.replace(/highlighted/, '');
		}
	}
	if (id) {
		let post = document.getElementById('reply_' + id);
		if (post) {
			post.className += ' highlighted';
		}
		window.location.hash = id;
	}
	return true;
}

function generatePassword() {
	let pass = '';
	let chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()_+';
	for (let i = 0; i < 8; i++) {
		let rnd = Math.floor(Math.random() * chars.length);
		pass += chars.substring(rnd, rnd + 1);
	}
	return pass;
}

function doPost(form) {
	if (form.elements['name']) {
		localStorage.name = form.elements['name'].value.replace(/( |^)## .+$/, '');
	}
	if (form.elements['password']) {
		localStorage.password = form.elements['password'].value;
	}
	if (form.elements['email'] && form.elements['email'].value != 'sage') {
		localStorage.email = form.elements['email'].value;
	}

	saved[document.location] = form.elements['body'].value;
	sessionStorage.body = JSON.stringify(saved);

	return form.elements['body'].value != "" || (form.elements['file'] && form.elements['file'].value != "") || (form.elements.file_url && form.elements['file_url'].value != "");
}

function citeReply(id, with_link) {
	let textarea = document.getElementById('body');
	if (!textarea) {
		return false;
	}

	if (textarea.selectionStart || textarea.selectionStart == '0') {
		let start = textarea.selectionStart;
		let end = textarea.selectionEnd;
		textarea.value = textarea.value.substring(0, start) + '>>' + id + '\n' + textarea.value.substring(end, textarea.value.length);

		textarea.selectionStart += ('>>' + id).length + 1;
		textarea.selectionEnd = textarea.selectionStart;
	} else {
		textarea.value += '>>' + id + '\n';
	}

	let select = window.getSelection ? window.getSelection().toString() : '';
	if (select) {
		let reply = document.getElementById('reply_' + id) || document.getElementById('op_' + id);
		let body = reply ? reply.querySelector('div.body') : null;
		if (body && body.textContent.indexOf(select.replace('\n', '')) > -1) {
			textarea.value += '>' + select + '\n';
		}
	}

	try {
		window.dispatchEvent(new CustomEvent('cite', { detail: { id: id, with_link: with_link } }));
	} catch (e) { /* ignore */ }
	textarea.dispatchEvent(new Event('change', { bubbles: true }));

	return false;
}

function rememberStuff() {
	if (document.forms.post) {
		if (document.forms.post.password) {
			if (!localStorage.password) {
				localStorage.password = generatePassword();
			}
			document.forms.post.password.value = localStorage.password;
		}

		if (localStorage.name && document.forms.post.elements['name']) {
			document.forms.post.elements['name'].value = localStorage.name;
		}
		if (localStorage.email && document.forms.post.elements['email']) {
			document.forms.post.elements['email'].value = localStorage.email;
		}

		if (window.location.hash.indexOf('q') == 1) {
			citeReply(window.location.hash.substring(2), true);
		}

		if (sessionStorage.body) {
			let saved = JSON.parse(sessionStorage.body);
			if (getCookie('serv')) {
				// Remove successful posts
				let successful = JSON.parse(getCookie('serv'));
				for (let url in successful) {
					saved[url] = null;
				}
				sessionStorage.body = JSON.stringify(saved);

				document.cookie = 'serv={};expires=0;path=/;';
			}
			if (saved[document.location]) {
				document.forms.post.body.value = saved[document.location];
			}
		}

		if (localStorage.body) {
			document.forms.post.body.value = localStorage.body;
			localStorage.body = '';
		}
	}
}

var script_settings = function(script_name) {
	this.script_name = script_name;
	this.get = function(var_name, default_val) {
		if (typeof tb_settings == 'undefined' ||
			typeof tb_settings[this.script_name] == 'undefined' ||
			typeof tb_settings[this.script_name][var_name] == 'undefined') {
			return default_val;
		}
		return tb_settings[this.script_name][var_name];
	}
};

function init() {
	initStyleChooser();

	
	
	

	if (window.location.hash.indexOf('q') != 1 && window.location.hash.substring(1))
		highlightReply(window.location.hash.substring(1));
}

var RecaptchaOptions = {
	theme : 'clean'
};

onready_callbacks = [];
function onReady(fnc) {
	onready_callbacks.push(fnc);
}

function ready() {
	for (let i = 0; i < onready_callbacks.length; i++) {
		onready_callbacks[i]();
	}
}



var post_date = "%m/%d/%y (%a) %H:%M:%S";
var max_images = 1;


onReady(init);
