<?php
/**
 * Local secrets — do not commit. Generated by tools/install_cli.php
 */

defined('TINYBOARD') or exit;

$config['db']['type']     = 'pgsql';
$config['db']['server']   = '127.0.0.1';
$config['db']['port']     = '5432';
$config['db']['database'] = 'board_app';
$config['db']['user']     = 'postgres';
$config['db']['password'] = 'adelia';

$config['cookies']['secure_login_only'] = 0;
$config['cookies']['salt'] = 'OSSL.pcNCbBa1R59yuQ1CksFQMGzALfxDFBTo/LTW5JHMxZPVAii/iJk5ZPGdsa0QOWWCPU1gD1quljogAOGWOnNyVA==';
$config['secure_trip_salt'] = 'OSSL.SCXtKR2CaK+TtndIq3y1PoBTItpVwRxKDBZqcEjWKTzdGH1MLbviVYiqeTXzFd4LkdphfMYzSmrADflvfY0F6w==';

$config['debug'] = false;
$config['verbose_errors'] = false;
